/*
    KP LIBERATION CRATEFILLER UI DEFINES

    File: defines.hpp
    Author: KP Liberation Dev Team - https://github.com/KillahPotatoes
    Date: 2019-05-02
    Last Update: 2019-05-04
    License: GNU General Public License v3.0 - https://www.gnu.org/licenses/gpl-3.0.html

    Description:
        Common defines for cratefiller module UI elements
*/

#define KPLIB_IDC_CRATEFILLER_DIALOG                758026

#define KPLIB_IDC_CRATEFILLER_GROUPOVERVIEW         687400

#define KPLIB_IDC_CRATEFILLER_COMBOGROUPS           687401
#define KPLIB_IDC_CRATEFILLER_COMBOPLAYERS          687402

#define KPLIB_IDC_CRATEFILLER_MAINWEAPON            687403
#define KPLIB_IDC_CRATEFILLER_HANDGUN               687404
#define KPLIB_IDC_CRATEFILLER_SECONDARYWEAPON       687405

#define KPLIB_IDC_CRATEFILLER_BUTTONOVERVIEW           687406

#define KPLIB_IDC_CRATEFILLER_COMBOCARGO            687407
#define KPLIB_IDC_CRATEFILLER_COMBOEQUIPMENT        687408
#define KPLIB_IDC_CRATEFILLER_COMBOWEAPONS          687409

#define KPLIB_IDC_CRATEFILLER_SEARCHBAR             687410

#define KPLIB_IDC_CRATEFILLER_LEFTEQUIPMENTBUTTON   687411
#define KPLIB_IDC_CRATEFILLER_RIGHTEQUIPMENTBUTTON  687412
#define KPLIB_IDC_CRATEFILLER_EQUIPMENTLIST         687413

#define KPLIB_IDC_CRATEFILLER_EXPORTNAME            687414
#define KPLIB_IDC_CRATEFILLER_IMPORTNAME            687415

#define KPLIB_IDC_CRATEFILLER_LEFTINVENTORYBUTTON   687416
#define KPLIB_IDC_CRATEFILLER_RIGHTINVENTORYBUTTON  687417
#define KPLIB_IDC_CRATEFILLER_INVENTORYLIST         687418

#define KPLIB_IDC_CRATEFILLER_PROGRESSBAR           687419
