
#define IDC_OVERLAY_RSC_PIC_BG 758001

#define IDC_OVERLAY_RSC_PIC_FOB 758002
#define IDC_OVERLAY_RSC_PIC_FOB_SHADOW 758003

#define IDC_OVERLAY_RSC_PIC_SUPPLIES 758005
#define IDC_OVERLAY_RSC_PIC_SUPPLIES_SHADOW 758006

#define IDC_OVERLAY_RSC_PIC_AMMO 758008
#define IDC_OVERLAY_RSC_PIC_AMMO_SHADOW 758009

#define IDC_OVERLAY_RSC_PIC_FUEL 758011
#define IDC_OVERLAY_RSC_PIC_FUEL_SHADOW 758012

#define IDC_OVERLAY_RSC_PIC_UNITCAP 758014
#define IDC_OVERLAY_RSC_PIC_UNITCAP_SHADOW 758015

#define IDC_OVERLAY_RSC_PIC_HELIPAD 758017
#define IDC_OVERLAY_RSC_PIC_HELIPAD_SHADOW 758018

#define IDC_OVERLAY_RSC_PIC_PLANE 758020
#define IDC_OVERLAY_RSC_PIC_PLANE_SHADOW 758021

// Combat readiness / enemy altertness
#define IDC_OVERLAY_RSC_PIC_ALERT 758023
#define IDC_OVERLAY_RSC_PIC_ALERT_SHADOW 758024

#define IDC_OVERLAY_RSC_PIC_CIVREP 758026
#define IDC_OVERLAY_RSC_PIC_CIVREP_SHADOW 758027

#define IDC_OVERLAY_RSC_PIC_INTEL 758029
#define IDC_OVERLAY_RSC_PIC_INTEL_SHADOW 758030

#define IDC_OVERLAY_RSC_LABEL_FOB 758004
#define IDC_OVERLAY_RSC_LABEL_SUPPLIES 758007
#define IDC_OVERLAY_RSC_LABEL_AMMO 758010
#define IDC_OVERLAY_RSC_LABEL_FUEL 758013
#define IDC_OVERLAY_RSC_LABEL_UNITCAP 758016
#define IDC_OVERLAY_RSC_LABEL_HELIPAD 758019
#define IDC_OVERLAY_RSC_LABEL_PLANE 758022
#define IDC_OVERLAY_RSC_LABEL_ALERT 758025
#define IDC_OVERLAY_RSC_LABEL_CIVREP 758028
#define IDC_OVERLAY_RSC_LABEL_INTEL 758031

#define OVERLAY_RSC_IDCS  [\
    IDC_OVERLAY_RSC_PIC_BG,\
    IDC_OVERLAY_RSC_PIC_FOB,\
    IDC_OVERLAY_RSC_PIC_FOB_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_FOB,\
    IDC_OVERLAY_RSC_PIC_SUPPLIES,\
    IDC_OVERLAY_RSC_PIC_SUPPLIES_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_SUPPLIES,\
    IDC_OVERLAY_RSC_PIC_AMMO,\
    IDC_OVERLAY_RSC_PIC_AMMO_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_AMMO,\
    IDC_OVERLAY_RSC_PIC_FUEL,\
    IDC_OVERLAY_RSC_PIC_FUEL_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_FUEL,\
    IDC_OVERLAY_RSC_PIC_UNITCAP,\
    IDC_OVERLAY_RSC_PIC_UNITCAP_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_UNITCAP,\
    IDC_OVERLAY_RSC_PIC_HELIPAD,\
    IDC_OVERLAY_RSC_PIC_HELIPAD_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_HELIPAD,\
    IDC_OVERLAY_RSC_PIC_PLANE,\
    IDC_OVERLAY_RSC_PIC_PLANE_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_PLANE,\
    IDC_OVERLAY_RSC_PIC_ALERT,\
    IDC_OVERLAY_RSC_PIC_ALERT_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_ALERT,\
    IDC_OVERLAY_RSC_PIC_CIVREP,\
    IDC_OVERLAY_RSC_PIC_CIVREP_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_CIVREP,\
    IDC_OVERLAY_RSC_PIC_INTEL,\
    IDC_OVERLAY_RSC_PIC_INTEL_SHADOW,\
    IDC_OVERLAY_RSC_LABEL_INTEL\
]
