/*
Needed Mods:
- None

Optional Mods:
- None
*/

// Enemy infantry classes
opfor_officer = 							"LIB_GER_oberst";									//Officer
opfor_squad_leader = 						"SG_sturmtrooper_lieutenant";						//Squad Leader
opfor_team_leader = 						"SG_sturmtrooper_unterofficer";						//Team Leader
opfor_sentry = 								"LIB_DAK_Sentry";									//Rifleman (Light) 
opfor_rifleman = 							"LIB_GER_rifleman";									//Rifleman 
opfor_rpg = 								"fow_s_ger_heer_rifleman_mp40_pzf";					//Rifleman (Panzerfaust) 
opfor_grenadier = 							"LIB_GER_AT_grenadier";								//Grenadier 
opfor_machinegunner = 						"fow_s_ger_heer_mg34_gunner";                  	    //Autorifleman 
opfor_heavygunner = 						"LIB_GER_mgunner";                             		//Heavy Gunner 
opfor_marksman = 							"fow_s_ger_heer_rifleman_g43";						//Marksman 
opfor_sharpshooter = 						"LIB_GER_scout_sniper";                    		    //Sharpshooter 
opfor_sniper = 								"SG_sturmtrooper_sniper";                     	    //Sniper 
opfor_at = 									"SG_sturmtrooper_AT_soldier";                		//AT Specialist 
opfor_aa = 									"SG_sturmtrooper_stggunner";						//Assault Gunner 
opfor_medic = 								"SG_sturmtrooper_medic";                            //Combat Life Saver 
opfor_engineer = 							"SG_sturmtrooper_sapper_gefr";                     	//Engineer
opfor_paratrooper = 						"LIB_FSJ_Soldier_2_para";                          	//Paratrooper

// Enemy vehicles used by secondary objectives.
opfor_mrap = 								"LIB_kfz1";											//Kuebelwagen
opfor_mrap_armed = 							"LIB_Kfz1_MG42";									//Kuebelwagen (MG42)
opfor_transport_helo = 						"ifa3_pzkpfwIV_H";									//Mi-290 Taru (Bench)
opfor_transport_truck = 					"LIB_opelblitz_tent_y_camo";						//Opel Blitz Transport (Covered)
opfor_ammobox_transport = 					"LIB_opelblitz_open_y_camo";						//Opel Blitz Transport (Open) -> Has to be able to transport resource crates!
opfor_fuel_truck = 							"LIB_opelblitz_fuel";								//Opel Blitz Fuel
opfor_ammo_truck = 							"LIB_opelblitz_ammo";								//Opel Blitz Ammo
opfor_fuel_container = 						"Land_Pod_Heli_Transport_04_fuel_F";				//Taru Fuel Pod
opfor_ammo_container = 						"Land_Pod_Heli_Transport_04_ammo_F";				//Taru Ammo Pod
opfor_flag = 								"geist_Flag_3Rc3_F";								//German Flag

/* Adding a value to these arrays below will add them to a one out of however many in the array, random pick chance.
Therefore, adding the same value twice or three times means they are more likely to be chosen more often. */

/* Militia infantry. Lightweight soldier classnames the game will pick from randomly as sector defenders.
Think of them like garrison or military police forces, which are more meant to control the local population instead of fighting enemy armies. */
militia_squad = [
    "LIB_GER_scout_mgunner",
    "LIB_GER_medic",
    "fow_s_ger_heer_rifleman_mp40_pzf",
    "LIB_GER_AT_grenadier",
    "LIB_GER_sapper_gefr",
    "LIB_GER_lieutenant",
    "LIB_GER_scout_unterofficer",
    "LIB_GER_radioman",
    "LIB_GER_ober_rifleman",
    "LIB_GER_scout_rifleman",
    "LIB_GER_scout_rifleman"
];

// Militia vehicles. Lightweight vehicle classnames the game will pick from randomly as sector defenders.
militia_vehicles = [
	"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",	"fow_v_truppenfahrrad_ger_heer",
	"R71Ger44",									"R71Ger44",									"R71Ger44",							"R71Ger44",
	"LIB_Kfz1_hood",
	"LIB_Kfz1_hood_camo",
	"LIB_Kfz1_hood_sernyt",
	"fow_v_kubelwagen_camo_ger_heer",
	"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",
	"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",
	"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",
	"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",
	"ifa3_gaz55_ger",							"ifa3_gaz55_ger",
	"lib_SdKfz_7",
	"lib_SdKfz_7_ammo",							"lib_SdKfz_7_ammo",
	"LIB_opelblitz_ambulance",					"LIB_opelblitz_ambulance",
	"LIB_opelblitz_ammo",						"LIB_opelblitz_ammo",
	"LIB_opelblitz_fuel",						"LIB_opelblitz_fuel",
	"LIB_opelblitz_parm",						"LIB_opelblitz_parm",
	"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",
	"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",
	"lib_SdKfz_7_AA",							"lib_SdKfz_7_AA",
	"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",
	"LIB_dak_M3_halftrack",
	"LIB_dak_scout_M3",
	"LIB_dak_scout_M3_ffv",
	"fow_v_sdkfz_251_camo_ger_heer",			"fow_v_sdkfz_251_camo_ger_heer",
	"fow_v_sdkfz_251_camo_foliage_ger_heer",	"fow_v_sdkfz_251_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",
	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",
	"ifa3_ba10_wm",
	"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",
	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",
	"fow_v_sdkfz_222_ger_heer",					"fow_v_sdkfz_222_ger_heer",
	"fow_v_sdkfz_222_foliage_ger_heer",			"fow_v_sdkfz_222_foliage_ger_heer",
	"fow_v_sdkfz_222_camo_ger_heer",			"fow_v_sdkfz_222_camo_ger_heer",
	"fow_v_sdkfz_222_camo_foliage_ger_heer",	"fow_v_sdkfz_222_camo_foliage_ger_heer",
	"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",
	"lib_sdkfz234_2",							"lib_sdkfz234_2",							"lib_sdkfz234_2",
	"lib_sdkfz234_3",							"lib_sdkfz234_3",							"lib_sdkfz234_3",
	"lib_sdkfz234_4",							"lib_sdkfz234_4",							"lib_sdkfz234_4"
];

// All enemy vehicles that can spawn as sector defenders and patrols at high enemy combat readiness (aggression levels).
opfor_vehicles = [
	"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",	"fow_v_truppenfahrrad_ger_heer",
	"R71Ger44",									"R71Ger44",									"R71Ger44",							"R71Ger44",
	"LIB_Kfz1_hood",
	"LIB_Kfz1_hood_camo",
	"LIB_Kfz1_hood_sernyt",
	"fow_v_kubelwagen_camo_ger_heer",
	"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",
	"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",
	"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",
	"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",
	"ifa3_gaz55_ger",							"ifa3_gaz55_ger",
	"lib_SdKfz_7",
	"lib_SdKfz_7_ammo",							"lib_SdKfz_7_ammo",
	"LIB_opelblitz_ambulance",					"LIB_opelblitz_ambulance",
	"LIB_opelblitz_ammo",						"LIB_opelblitz_ammo",
	"LIB_opelblitz_fuel",						"LIB_opelblitz_fuel",
	"LIB_opelblitz_parm",						"LIB_opelblitz_parm",
	"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",
	"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",
	"lib_SdKfz_7_AA",							"lib_SdKfz_7_AA",
	"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",
	"LIB_dak_M3_halftrack",
	"LIB_dak_scout_M3",
	"LIB_dak_scout_M3_ffv",
	"fow_v_sdkfz_251_camo_ger_heer",			"fow_v_sdkfz_251_camo_ger_heer",
	"fow_v_sdkfz_251_camo_foliage_ger_heer",	"fow_v_sdkfz_251_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",
	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",
	"ifa3_ba10_wm",
	"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",
	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",
	"fow_v_sdkfz_222_ger_heer",					"fow_v_sdkfz_222_ger_heer",
	"fow_v_sdkfz_222_foliage_ger_heer",			"fow_v_sdkfz_222_foliage_ger_heer",
	"fow_v_sdkfz_222_camo_ger_heer",			"fow_v_sdkfz_222_camo_ger_heer",
	"fow_v_sdkfz_222_camo_foliage_ger_heer",	"fow_v_sdkfz_222_camo_foliage_ger_heer",
	"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",
	"lib_sdkfz234_2",							"lib_sdkfz234_2",							"lib_sdkfz234_2",
	"lib_sdkfz234_3",							"lib_sdkfz234_3",							"lib_sdkfz234_3",
	"lib_sdkfz234_4",							"lib_sdkfz234_4",							"lib_sdkfz234_4",
	"pz2f",										"pz2f",										"pz2f",
	"pz2f2",									"pz2f2",									"pz2f2",
	"ifa3_pz3j",								"ifa3_pz3j",								"ifa3_pz3j",
	"ifa3_pz3n",								"ifa3_pz3n",								"ifa3_pz3n",
	"Lib_pzkpfwIV_H",							"Lib_pzkpfwIV_H",
	"ifa3_pzkpfwIV_H",							"ifa3_pzkpfwIV_H",
	"Lib_pzkpfwIV_H_tarn51c",					"Lib_pzkpfwIV_H_tarn51c",
	"Lib_pzkpfwIV_H_tarn51d",					"Lib_pzkpfwIV_H_tarn51d",
	"LIB_PzKpfwV",								"LIB_PzKpfwV",
	"ifa3_stug_III_g",							"ifa3_stug_III_g",
	"LIb_stug_III_g",							"LIb_stug_III_g",
	"ifa3_stuh_42",								"ifa3_stuh_42",
	"Lib_SdKfz124",
	"Lib_FlakpanzerIV_Wirbelwind",
	"Lib_PzKpfwVI_E",							"Lib_PzKpfwVI_E_1",	
	"Lib_PzKpfwVI_B",							"Lib_PzKpfwVI_B_tarn51c"
];

// All enemy vehicles that can spawn as sector defenders and patrols but at a lower enemy combat readiness (aggression levels).
opfor_vehicles_low_intensity = [
	"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",	"fow_v_truppenfahrrad_ger_heer",
	"R71Ger44",									"R71Ger44",									"R71Ger44",							"R71Ger44",
	"LIB_Kfz1_hood",
	"LIB_Kfz1_hood_camo",
	"LIB_Kfz1_hood_sernyt",
	"fow_v_kubelwagen_camo_ger_heer",
	"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",
	"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",
	"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",
	"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",
	"ifa3_gaz55_ger",							"ifa3_gaz55_ger",
	"lib_SdKfz_7",
	"lib_SdKfz_7_ammo",							"lib_SdKfz_7_ammo",
	"LIB_opelblitz_ambulance",					"LIB_opelblitz_ambulance",
	"LIB_opelblitz_ammo",						"LIB_opelblitz_ammo",
	"LIB_opelblitz_fuel",						"LIB_opelblitz_fuel",
	"LIB_opelblitz_parm",						"LIB_opelblitz_parm",
	"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",
	"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",
	"lib_SdKfz_7_AA",							"lib_SdKfz_7_AA",
	"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",
	"LIB_dak_M3_halftrack",
	"LIB_dak_scout_M3",
	"LIB_dak_scout_M3_ffv",
	"fow_v_sdkfz_251_camo_ger_heer",			"fow_v_sdkfz_251_camo_ger_heer",
	"fow_v_sdkfz_251_camo_foliage_ger_heer",	"fow_v_sdkfz_251_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",
	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",
	"ifa3_ba10_wm",
	"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",
	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",
	"fow_v_sdkfz_222_ger_heer",					"fow_v_sdkfz_222_ger_heer",
	"fow_v_sdkfz_222_foliage_ger_heer",			"fow_v_sdkfz_222_foliage_ger_heer",
	"fow_v_sdkfz_222_camo_ger_heer",			"fow_v_sdkfz_222_camo_ger_heer",
	"fow_v_sdkfz_222_camo_foliage_ger_heer",	"fow_v_sdkfz_222_camo_foliage_ger_heer",
	"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",
	"lib_sdkfz234_2",							"lib_sdkfz234_2",							"lib_sdkfz234_2",
	"lib_sdkfz234_3",							"lib_sdkfz234_3",							"lib_sdkfz234_3",
	"lib_sdkfz234_4",							"lib_sdkfz234_4",							"lib_sdkfz234_4",
	"pz2f",										"pz2f",
	"pz2f2",									"pz2f2"
];

// All enemy vehicles that can spawn as battlegroups, either assaulting or as reinforcements, at high enemy combat readiness (aggression levels).
opfor_battlegroup_vehicles = [
	"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",	"fow_v_truppenfahrrad_ger_heer",
	"R71Ger44",									"R71Ger44",									"R71Ger44",							"R71Ger44",
	"LIB_Kfz1_hood",
	"LIB_Kfz1_hood_camo",
	"LIB_Kfz1_hood_sernyt",
	"fow_v_kubelwagen_camo_ger_heer",
	"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",
	"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",
	"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",
	"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",
	"ifa3_gaz55_ger",							"ifa3_gaz55_ger",
	"lib_SdKfz_7",
	"lib_SdKfz_7_ammo",							"lib_SdKfz_7_ammo",
	"LIB_opelblitz_ambulance",					"LIB_opelblitz_ambulance",
	"LIB_opelblitz_ammo",						"LIB_opelblitz_ammo",
	"LIB_opelblitz_fuel",						"LIB_opelblitz_fuel",
	"LIB_opelblitz_parm",						"LIB_opelblitz_parm",
	"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",
	"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",
	"lib_SdKfz_7_AA",							"lib_SdKfz_7_AA",
	"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",
	"LIB_dak_M3_halftrack",
	"LIB_dak_scout_M3",
	"LIB_dak_scout_M3_ffv",
	"fow_v_sdkfz_251_camo_ger_heer",			"fow_v_sdkfz_251_camo_ger_heer",
	"fow_v_sdkfz_251_camo_foliage_ger_heer",	"fow_v_sdkfz_251_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",
	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",
	"ifa3_ba10_wm",
	"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",
	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",
	"fow_v_sdkfz_222_ger_heer",					"fow_v_sdkfz_222_ger_heer",
	"fow_v_sdkfz_222_foliage_ger_heer",			"fow_v_sdkfz_222_foliage_ger_heer",
	"fow_v_sdkfz_222_camo_ger_heer",			"fow_v_sdkfz_222_camo_ger_heer",
	"fow_v_sdkfz_222_camo_foliage_ger_heer",	"fow_v_sdkfz_222_camo_foliage_ger_heer",
	"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",
	"lib_sdkfz234_2",							"lib_sdkfz234_2",							"lib_sdkfz234_2",
	"lib_sdkfz234_3",							"lib_sdkfz234_3",							"lib_sdkfz234_3",
	"lib_sdkfz234_4",							"lib_sdkfz234_4",							"lib_sdkfz234_4",
	"pz2f",										"pz2f",										"pz2f",
	"pz2f2",									"pz2f2",									"pz2f2",
	"ifa3_pz3j",								"ifa3_pz3j",								"ifa3_pz3j",
	"ifa3_pz3n",								"ifa3_pz3n",								"ifa3_pz3n",
	"Lib_pzkpfwIV_H",							"Lib_pzkpfwIV_H",
	"ifa3_pzkpfwIV_H",							"ifa3_pzkpfwIV_H",
	"Lib_pzkpfwIV_H_tarn51c",					"Lib_pzkpfwIV_H_tarn51c",
	"Lib_pzkpfwIV_H_tarn51d",					"Lib_pzkpfwIV_H_tarn51d",
	"LIB_PzKpfwV",								"LIB_PzKpfwV",
	"ifa3_stug_III_g",							"ifa3_stug_III_g",
	"LIb_stug_III_g",							"LIb_stug_III_g",
	"ifa3_stuh_42",								"ifa3_stuh_42",
	"Lib_SdKfz124",
	"Lib_FlakpanzerIV_Wirbelwind",
	"Lib_PzKpfwVI_E",
	"Lib_PzKpfwVI_E_1",
	"Lib_PzKpfwVI_E_2",
	"Lib_PzKpfwVI_E_tarn51c",
	"Lib_PzKpfwVI_E_tarn51d",
	"Lib_PzKpfwVI_E_tarn52c",
	"Lib_PzKpfwVI_E_tarn52d",
	"Lib_PzKpfwVI_B",
	"Lib_PzKpfwVI_B_tarn51c",
	"Lib_PzKpfwVI_B_tarn51d"
];

// All enemy vehicles that can spawn as battlegroups, either assaulting or as reinforcements, at lower enemy combat readiness (aggression levels).
opfor_battlegroup_vehicles_low_intensity = [
	"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",			"fow_v_truppenfahrrad_ger_heer",	"fow_v_truppenfahrrad_ger_heer",
	"R71Ger44",									"R71Ger44",									"R71Ger44",							"R71Ger44",
	"LIB_Kfz1_hood",
	"LIB_Kfz1_hood_camo",
	"LIB_Kfz1_hood_sernyt",
	"fow_v_kubelwagen_camo_ger_heer",
	"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",							"LIB_Kfz1_MG42",
	"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",						"LIB_Kfz1_MG42_camo",
	"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",						"LIB_Kfz1_MG42_sernyt",
	"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",			"fow_v_kubelwagen_mg34_ger_heer",
	"ifa3_gaz55_ger",							"ifa3_gaz55_ger",
	"lib_SdKfz_7",
	"lib_SdKfz_7_ammo",							"lib_SdKfz_7_ammo",
	"LIB_opelblitz_ambulance",					"LIB_opelblitz_ambulance",
	"LIB_opelblitz_ammo",						"LIB_opelblitz_ammo",
	"LIB_opelblitz_fuel",						"LIB_opelblitz_fuel",
	"LIB_opelblitz_parm",						"LIB_opelblitz_parm",
	"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",				"LIB_opelblitz_open_y_camo",
	"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",				"LIB_opelblitz_tent_y_camo",
	"lib_SdKfz_7_AA",							"lib_SdKfz_7_AA",
	"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",							"LIB_SdKfz251_FFV",
	"LIB_dak_M3_halftrack",
	"LIB_dak_scout_M3",
	"LIB_dak_scout_M3_ffv",
	"fow_v_sdkfz_251_camo_ger_heer",			"fow_v_sdkfz_251_camo_ger_heer",
	"fow_v_sdkfz_251_camo_foliage_ger_heer",	"fow_v_sdkfz_251_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",					"fow_v_sdkfz_250_ger_heer",
	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",	"fow_v_sdkfz_250_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",			"fow_v_sdkfz_250_camo_ger_heer",
	"ifa3_ba10_wm",
	"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",				"fow_v_sdkfz_250_9_ger_heer",
	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",	"fow_v_sdkfz_250_9_camo_foliage_ger_heer",
	"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",			"fow_v_sdkfz_250_9_camo_ger_heer",
	"fow_v_sdkfz_222_ger_heer",					"fow_v_sdkfz_222_ger_heer",
	"fow_v_sdkfz_222_foliage_ger_heer",			"fow_v_sdkfz_222_foliage_ger_heer",
	"fow_v_sdkfz_222_camo_ger_heer",			"fow_v_sdkfz_222_camo_ger_heer",
	"fow_v_sdkfz_222_camo_foliage_ger_heer",	"fow_v_sdkfz_222_camo_foliage_ger_heer",
	"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",						"fow_v_sdkfz_234_1",
	"lib_sdkfz234_2",							"lib_sdkfz234_2",							"lib_sdkfz234_2",
	"lib_sdkfz234_3",							"lib_sdkfz234_3",							"lib_sdkfz234_3",
	"lib_sdkfz234_4",							"lib_sdkfz234_4",							"lib_sdkfz234_4",
	"pz2f",										"pz2f",
	"pz2f2",									"pz2f2"
];

/* All vehicles that spawn within battlegroups (see the above 2 arrays) and also hold 8 soldiers as passengers.
If something in this array can't hold all 8 soldiers then buggy behaviours may occur.	*/
opfor_troup_transports = [
	"LIB_opelblitz_open_y_camo",
	"LIB_opelblitz_tent_y_camo",
	"LIB_SdKfz251_FFV",
	"LIB_dak_M3_halftrack",
	"LIB_dak_scout_M3",
	"LIB_dak_scout_M3_ffv",
	"fow_v_sdkfz_251_camo_ger_heer",
	"fow_v_sdkfz_251_camo_foliage_ger_heer",
	"ifa3_gaz55_ger"
];

// Enemy rotary-wings that will need to spawn in flight.
opfor_choppers = [
	"LIB_avia_camo",
	"LIB_avia_grey",
	"LIB_bf110_brown",
	"LIB_bf110_brown_at",
	"LIB_bf110_brown_cas",
	"LIB_bf110_geist_camo_1nap",
	"LIB_bf110_geist_camo_2nbp",
	"LIB_bf110_geist_camo_2ncp",
	"LIB_bf110_geist_camo_2ndp",
	"LIB_bf110_geist_camo_2nbp_at",
	"LIB_bf110_geist_camo_m8kh_at",
	"LIB_bf110_geist_camo_2nbp_cas",
	"LIB_bf110_geist_camo_m8kh_cas",
	"LIB_bf110_geist_camo_m8ah",
	"LIB_bf110_geist_camo_m8dh",
	"LIB_bf110_geist_camo_m8hh",
	"LIB_bf110_geist_camo_m8kh",
	"LIB_bf110_grey",
	"LIB_bf110_grey_at",
	"LIB_bf110_grey_cas",
	"LIB_bf110_geist_nacht_9win",
	"LIB_bf110_geist_nacht_9wan",
	"LIB_bf110_geist_nacht_9wdn",
	"LIB_bf110_geist_nacht_9wmn",
	"LIB_bf110_geist_nacht_9wan_at",
	"LIB_bf110_geist_nacht_9wan_cas",
	"LIB_bv141_brown",
	"LIB_bv141_green",
	"LIB_bv141_grey",
	"LIB_do335_black",
	"LIB_do335_green",
	"ifa3_FW190F8",
	"lib_FW190F8",
	"lib_FW190F8_italy",
	"lib_FW190F8_5",
	"lib_FW190F8_4",
	"lib_FW190F8_2",
	"lib_FW190F8_3",
	"lib_he111_green",
	"lib_he111_geist_camo_a1ab",
	"lib_he111_geist_camo_a1ah",
	"lib_he111_geist_camo_a1bt",
	"lib_he111_geist_camo_a1ch",
	"lib_he111_geist_camo_a1hl",
	"lib_he111_geist_camo_a1ht",
	"lib_he111_geist_camo_a1ih",
	"lib_he111_geist_camo_a1kt",
	"lib_he111_geist_camo_a1ll",
	"lib_he111_geist_camo_a1nl",
	"lib_he111_grey",
	"lib_hix_black",
	"lib_hix_brown",
	"lib_hix_green",
	"lib_ju52",
	"lib_w34",
	"lib_w34_floats",
	"lib_me262_brown",
	"lib_me262_green",
	"lib_me262_night",
	"sab_avia",
	"sab_natter",
	"sab_bf110",
	"sab_bf110_2",
	"sab_bv141",
	"sab_hix",
	"sab_he111",
	"sab_ju87",
	"sab_me262",
	"sab_me262_2",
	"sab_w34",
	"sab_w34f",
	"sab_do335",
	"sab_fiatg55",
	"lib_avia_afrika",
	"lib_ju87",
	"lib_ju87_camo_antitank",
	"lib_ju87_camo_bombs",
	"lib_ju87_camo_cas",
	"lib_ju87_italy",
	"lib_ju87_italy_2",
	"lib_dak_ju87",
	"lib_dak_ju87_2",
	"lib_aar_ju87",
	"lib_mkhl_ju87",
	"lib_rbaf_ju87",
	"ifa3_ju87_1x500",
	"ifa3_ju87_4x50",
	"LIB_bf110_geist_afrika_3uar",
	"LIB_bf110_geist_afrika_3ucr",
	"LIB_bf110_geist_afrika_3udr",
	"LIB_bf110_geist_afrika_3ufr",
	"LIB_bf110_geist_afrika_3ucr_at",
	"LIB_bf110_geist_afrika_3ucr_cas",
	"Lib_dak_FW190F8",
	"Lib_dak_FW190F8_desert2",
	"Lib_dak_FW190F8_desert3",
	"Lib_dak_FW190F8_desert"
];

// Enemy fixed-wings that will need to spawn in the air.
opfor_air = [
	"LIB_avia_camo",
	"LIB_avia_grey",
	"LIB_bf110_brown",
	"LIB_bf110_brown_at",
	"LIB_bf110_brown_cas",
	"LIB_bf110_geist_camo_1nap",
	"LIB_bf110_geist_camo_2nbp",
	"LIB_bf110_geist_camo_2ncp",
	"LIB_bf110_geist_camo_2ndp",
	"LIB_bf110_geist_camo_2nbp_at",
	"LIB_bf110_geist_camo_m8kh_at",
	"LIB_bf110_geist_camo_2nbp_cas",
	"LIB_bf110_geist_camo_m8kh_cas",
	"LIB_bf110_geist_camo_m8ah",
	"LIB_bf110_geist_camo_m8dh",
	"LIB_bf110_geist_camo_m8hh",
	"LIB_bf110_geist_camo_m8kh",
	"LIB_bf110_grey",
	"LIB_bf110_grey_at",
	"LIB_bf110_grey_cas",
	"LIB_bf110_geist_nacht_9win",
	"LIB_bf110_geist_nacht_9wan",
	"LIB_bf110_geist_nacht_9wdn",
	"LIB_bf110_geist_nacht_9wmn",
	"LIB_bf110_geist_nacht_9wan_at",
	"LIB_bf110_geist_nacht_9wan_cas",
	"LIB_bv141_brown",
	"LIB_bv141_green",
	"LIB_bv141_grey",
	"LIB_do335_black",
	"LIB_do335_green",
	"ifa3_FW190F8",
	"lib_FW190F8",
	"lib_FW190F8_italy",
	"lib_FW190F8_5",
	"lib_FW190F8_4",
	"lib_FW190F8_2",
	"lib_FW190F8_3",
	"lib_he111_green",
	"lib_he111_geist_camo_a1ab",
	"lib_he111_geist_camo_a1ah",
	"lib_he111_geist_camo_a1bt",
	"lib_he111_geist_camo_a1ch",
	"lib_he111_geist_camo_a1hl",
	"lib_he111_geist_camo_a1ht",
	"lib_he111_geist_camo_a1ih",
	"lib_he111_geist_camo_a1kt",
	"lib_he111_geist_camo_a1ll",
	"lib_he111_geist_camo_a1nl",
	"lib_he111_grey",
	"lib_hix_black",
	"lib_hix_brown",
	"lib_hix_green",
	"lib_ju52",
	"lib_w34",
	"lib_w34_floats",
	"lib_me262_brown",
	"lib_me262_green",
	"lib_me262_night",
	"sab_avia",
	"sab_natter",
	"sab_bf110",
	"sab_bf110_2",
	"sab_bv141",
	"sab_hix",
	"sab_he111",
	"sab_ju87",
	"sab_me262",
	"sab_me262_2",
	"sab_w34",
	"sab_w34f",
	"sab_do335",
	"sab_fiatg55",
	"lib_avia_afrika",
	"lib_ju87",
	"lib_ju87_camo_antitank",
	"lib_ju87_camo_bombs",
	"lib_ju87_camo_cas",
	"lib_ju87_italy",
	"lib_ju87_italy_2",
	"lib_dak_ju87",
	"lib_dak_ju87_2",
	"lib_aar_ju87",
	"lib_mkhl_ju87",
	"lib_rbaf_ju87",
	"ifa3_ju87_1x500",
	"ifa3_ju87_4x50",
	"LIB_bf110_geist_afrika_3uar",
	"LIB_bf110_geist_afrika_3ucr",
	"LIB_bf110_geist_afrika_3udr",
	"LIB_bf110_geist_afrika_3ufr",
	"LIB_bf110_geist_afrika_3ucr_at",
	"LIB_bf110_geist_afrika_3ucr_cas",
	"Lib_dak_FW190F8",
	"Lib_dak_FW190F8_desert2",
	"Lib_dak_FW190F8_desert3",
	"Lib_dak_FW190F8_desert"
];
