// If left empty, everything is allowed, otherwise only whitelisted items will be available
GRLIB_arsenal_weapons = [
"Hatchet",
"KA_knife",
"LEN_StenMk5",
"LEN_StenMk2S",
"LEN_StenMk2",
"LEN_SMLENo4Mk1T",
"LEN_SMLENo4Mk1",
"LEN_M3a1",
"LIB_MG34",
"LIB_Mg34_PT",
"LIB_MG42",
"LIB_M2_Flamethrower",
"LIB_M1A1_Thompson",
"LIB_M1A1_Carbine",
"LIB_M1919A6",
"LIB_M1918A2_BAR",
"LIB_M1903A4_Springfield",
"LIB_M1_Garand",
"LIB_DELISLE",
"fow_w_piat",
"fow_w_M1912",
"fow_w_m55_reising",
"fow_w_leeenfield_no5mk1_junglecarbine",
"fow_w_bren",
"fow_w_leeenfield_no4mk1",
"fow_w_leeenfield_no4mk1_redwood",
"LIB_PTRD",
"LIB_PTRD_optic",
"fow_w_webley",
"fow_w_m1911",
"KA_TL_122_flashlight",
"LIB_kampf_PISTOL",
"LIB_FLARE_PISTOL",
"LIB_M2_Tripod",
"LIB_M2_60_Tripod",
"LIB_M2_60_Barrel",
"LIB_M1A1_Bazooka",
"fow_w_wellrod_mkii",
"fow_w_m1a1_bazooka",
"LIB_Binoculas_US",
"G_LIB_Binoculars"
];

GRLIB_arsenal_magazines = [

];

GRLIB_arsenal_items = [
"ItemWatch",
"ItemRadio",
"tf_anprc152",
"tf_anprc154",
"ItemMap",
"MineDetector",
"Binocular",
"FirstAidKit",
"ItemMap",
"ItemCompass",
"LIB_ToolKit",
"ItemWatch",
"Medikit",
"ToolKit",
"G_LIB_Binoculars",
"fow_u_aus_m37_02_private",
"fow_u_aus_m37_03_private",
"fow_u_aus_m37_01_private",
"fow_h_uk_jungle_hat_01",
"fow_h_uk_jungle_hat_02",
"fow_h_uk_mk2",
"fow_h_uk_mk2_net",
"fow_h_uk_mk2_net_foliage",
"fow_h_uk_mk2_net_foliage_camo",
"fow_v_us_medic",
"fow_v_uk_base_green",
"fow_v_uk_bren",
"fow_v_uk_officer",
"fow_v_uk_para_sten",
"fow_v_uk_sten_green",
"fow_v_uk_bren_green",
"fow_v_uk_base",
"fow_u_us_pilot_01",
"fow_h_uk_beret_rtr",
"fow_v_us_45",
"H_LIB_US_Helmet_Pilot",
"V_LIB_US_LifeVest",
"U_LIB_US_Pilot",
"fow_h_uk_beret_commando",
"fow_u_uk_bd40_commando_01_private",
"G_LIB_Dienst_Brille",
"G_LIB_Dienst_Brille2",
"G_LIB_Dust_Goggles",
"G_LIB_GER_Gloves1",
"G_LIB_GER_Gloves2",
"G_LIB_GER_Gloves3",
"G_LIB_GER_Gloves4",
"G_LIB_Watch1",
"G_LIB_Watch2",
"LIB_ACC_GW_SB_Empty",
"G_LIB_Scarf2_B",
"G_LIB_Scarf2_G",
"G_LIB_Scarf_B",
"G_LIB_Scarf_G",
"H_HeadBandage_bloody_F",
"H_HeadBandage_stained_F",
"H_HeadBandage_clean_F",
"G_LIB_Mohawk",
"Len_ACC_M1897_Bayo",        				//LEN-Pack
"sab_wwiplanes_pilot_holster",           	//SABRE-Pack
"tf_anprc148jem_3",        					//TFAR
"tf_anprc148jem_4",        					//TFAR
"tf_anprc152_1",           					//TFAR
"tf_fadak_1",              					//TFAR
"tf_pnr1000a_1",           					//TFAR
"ACE_atropine",                  			 //ACE
"ACE_fieldDressing",             			 //ACE
"ACE_elasticBandage",            			 //ACE
"ACE_quikclot",                  			 //ACE
"ACE_bloodIV",                   			 //ACE
"ACE_bloodIV_500",               			 //ACE
"ACE__bloodIV_250",              			 //ACE
"ACE_bodyBag",                   			 //ACE
"ACE_bodyBagObject",             			 //ACE
"ACE_epinephrine",               			 //ACE
"ACE_morphine",                 			  //ACE
"ACE_packingBandage",         	 			  //ACE
"ACE_personalAidKit",           		     //ACE
"ACE_plasmaIV",                 			 //ACE
"ACE_plasmaIV_500",              			 //ACE
"ACE_plasmaIV_250",             		     //ACE
"ACE_salineIV",                  			 //ACE
"ACE_salineIV_500",              			 //ACE
"ACE_salineIV_250",                			 //ACE
"ACE_surgicalKit",               			 //ACE
"ACE_tourniquet",                 			 //ACE
"ACE_EarPlugs",
"ACE_CableTie",
"ACE_EntrenchingTool",
"ACE_Clacker",
"ACE_MapTools",
"ACE_wirecutter",
"fow_i_whistle",
"fow_i_fak_carlisle_M43",
"ACE_Chemlight_White",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiYellow",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiOrange",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"Chemlight_blue",
"Chemlight_green",
"Chemlight_red",
"Chemlight_yellow",
"ACE_HandFlare_Green",
"ACE_HandFlare_Red",
"ACE_HandFlare_Yellow",
"ACE_HandFlare_White",
"Lib_us_Mk2",
"fow_e_no36mk1",
"fow_e_69",
"fow_e_73",
"fow_e_77",
"LIB_Rpg6",
"fow_e_79",
"fow_e_82",
"LIB_US_M18",
"LIB_US_M18_Yellow",
"LIB_US_M18_Green",
"LIB_US_M18_Red",
"ifa3_TS_Small",
"fow_e_tnt_twohalfpound_mag",
"fow_e_tnt_onepound_mag",
"fow_e_tnt_twopound_mag",
"tf_rt1523g",
"tf_rt1523g_big",
"tf_rt1523g_green",
"tf_rt1523g_big_bwmod",
"tf_rt1523g_big_bwmod_tropen",
"LIB_Binoculars_US",
"G_LIB_Binoculars",
"fow_u_uk_parasmock",
"fow_u_uk_bd40_seac_01_corporal",
"fow_u_uk_bd40_seac_01_lance-corporal",
"fow_u_uk_bd40_seac_01_lieutenent",
"fow_u_uk_bd40_seac_01_private",
"fow_u_uk_bd40_seac_01_sergeant",
"fow_u_uk_bd40_seac_02_corporal",
"fow_u_uk_bd40_seac_02_lance-corporal",
"fow_u_uk_bd40_seac_02_lieutenent",
"fow_u_uk_bd40_seac_02_private",
"fow_u_uk_bd40_seac_02_sergeant",
"U_LIB_US_Rangers_Uniform",
"U_LIB_US_Rangers_Corp",
"U_LIB_US_Rangers_Med",
"U_LIB_US_Rangers_Private_1st",
"U_LIB_US_Rangers_Sergeant",
"U_LIB_US_Rangers_Eng",
"U_LIB_US_Med",
"U_LIB_US_NAC_Uniform",
"U_LIB_US_NAC_Med",
"U_LIB_US_NAC_Uniform_2",
"fow_h_uk_woolen_hat",
"H_LIB_NKVD_OfficerCap",
"U_LIB_US_AB_Uniform_M43_NCO",
"V_LIB_US_AB_Vest_Carbine_nco_Radio",
"H_LIB_US_AB_Helmet_NCO_1",
"U_LIB_US_AB_Uniform_M43_Medic",
"H_LIB_US_AB_Helmet_Medic_1",
"LIB_US_M1A1_ATMINE_mag",
"LIB_M3_MINE_mag"
];

GRLIB_arsenal_backpacks = [
"fow_b_uk_bergenpack",
"fow_b_uk_piat",
"fow_b_uk_p37_blanco",
"fow_b_uk_p37",
"fow_b_uk_p37_radio_blanco",
"fow_b_uk_p37_radio",
"fow_b_uk_p37_blanco_shovel",
"fow_b_uk_p37_shovel",
"fow_b_uk_vickers_support",
"fow_b_usa_m1919_support",
"fow_b_usa_m1919_weapon",
"fow_b_uk_vickers_weapon",
"fow_b_uk_piat",
"B_LIB_US_TypeA3",
"B_LIB_US_M2Flamethrower",
"tf_rt1523g",
"tf_rt1523g_big",
"tf_rt1523g_green",
"tf_rt1523g_big_bwmod",
"tf_rt1523g_big_bwmod_tropen",
"B_Carryall_ocamo"
];