/*
    KP LIBERATION LOGISTIC UI DEFINES

    File: defines.hpp
    Author: KP Liberation Dev Team - https://github.com/KillahPotatoes
    Date: 2019-05-02
    Last Update: 2019-05-02
    License: GNU General Public License v3.0 - https://www.gnu.org/licenses/gpl-3.0.html

    Description:
        Common defines for logistic module UI elements
*/

// Main dialog
#define KPLIB_IDC_LOGISTIC_MAIN_DIALOG                  7580231

// Recycle dialog
#define KPLIB_IDC_LOGISTIC_RECYCLE_DIALOG               7580232

#define KPLIB_IDC_LOGISTIC_RECYCLE_COMBOVEHICLES        687400

#define KPLIB_IDC_LOGISTIC_RECYCLE_SUPPLYSTATEVALUE     687401
#define KPLIB_IDC_LOGISTIC_RECYCLE_SUPPLYREFUNDVALUE    687402

#define KPLIB_IDC_LOGISTIC_RECYCLE_AMMOSTATEVALUE       687403
#define KPLIB_IDC_LOGISTIC_RECYCLE_AMMOREFUNDVALUE      687404

#define KPLIB_IDC_LOGISTIC_RECYCLE_FUELSTATEVALUE       687405
#define KPLIB_IDC_LOGISTIC_RECYCLE_FUELREFUNDVALUE      687406

#define KPLIB_IDC_LOGISTIC_RECYCLE_BUTTONRECYCLE        687407

// Resupply dialog
#define KPLIB_IDC_LOGISTIC_RESUPPLY_DIALOG              7580233

#define KPLIB_IDC_LOGISTIC_RESUPPLY_COMBOVEHICLES       687400
#define KPLIB_IDC_LOGISTIC_RESUPPLY_COMBOCARGO          687401

#define KPLIB_IDC_LOGISTIC_RESUPPLY_CARGOSTATEVALUE     687402
#define KPLIB_IDC_LOGISTIC_RESUPPLY_CARGOCOSTSVALUE     687403

#define KPLIB_IDC_LOGISTIC_RESUPPLY_RESUPPLYCOUNT       687404

#define KPLIB_IDC_LOGISTIC_RESUPPLY_SLIDERVALUE         687405

#define KPLIB_IDC_LOGISTIC_RESUPPLY_TOTALCOSTSVALUE     687406

#define KPLIB_IDC_LOGISTIC_RESUPPLY_BUTTONRESUPPLY      687407
