uisleep 0.1;
camo_class_names = nil;
camo_display_names = nil;
comp_class_names = nil;
comp_display_names = nil;
current_comp = nil;
VAM_camo_check_complete = nil;
VAM_comp_check_complete = nil;
VAM_check_fnc_delay = nil;
VAM_targetvehicle = nil;