name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: docker://node:20-alpine
        name: Setup Node

      - name: Install dependencies
        working-directory: _tools/build-tool
        run: npm install

      - name: Assemble and pack
        working-directory: _tools/build-tool
        run: npx gulp

      - uses: actions/upload-artifact@master
        with:
          name: PBO-Files
          path: build/pbo

